version: '3'

services:
  db:
    image: postgres
    environment:
     POSTGRES_DB: ${POSTGRES_DB}
     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
     POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  web:
    build: .
    command: ["gunicorn", "postfirerecovery.wsgi:application", "--bind", "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=False

  nginx:
    image: nginx:1.19
    ports:
      - "80:80"
    volumes:
      # - ./nginx:/etc/nginx/conf.d/default.conf
      - ./nginx/postfirerecovery.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - web

volumes:
  postgres_data:
