# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-11 05:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactus'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contactus',
            table='"users_contact_us"',
        ),
    ]
